const RESOURCES = {
  WOOD: 'Wood',
  BRICK: 'Brick',
  SHEEP: 'Sheep',
  WHEAT: 'Wheat',
  ORE: 'Ore',
  DESERT: 'Desert',
  OCEAN: 'Ocean'
};

const PORT_TYPES = {
  THREE_TO_ONE: '3:1',
  WOOD_2_TO_1: 'Wood 2:1',
  BRICK_2_TO_1: 'Brick 2:1',
  SHEEP_2_TO_1: 'Sheep 2:1',
  WHEAT_2_TO_1: 'Wheat 2:1',
  ORE_2_TO_1: 'Ore 2:1'
};

const INITIAL_PORTS = [
  ...Array(4).fill(PORT_TYPES.THREE_TO_ONE),
  PORT_TYPES.WOOD_2_TO_1,
  PORT_TYPES.BRICK_2_TO_1,
  PORT_TYPES.SHEEP_2_TO_1,
  PORT_TYPES.WHEAT_2_TO_1,
  PORT_TYPES.ORE_2_TO_1
];

const BUILDING_COSTS = {
  ROAD: { [RESOURCES.WOOD]: 1, [RESOURCES.BRICK]: 1 },
  SETTLEMENT: { [RESOURCES.WOOD]: 1, [RESOURCES.BRICK]: 1, [RESOURCES.WHEAT]: 1, [RESOURCES.SHEEP]: 1 },
  CITY: { [RESOURCES.WHEAT]: 2, [RESOURCES.ORE]: 3 },
  DEV_CARD: { [RESOURCES.WHEAT]: 1, [RESOURCES.SHEEP]: 1, [RESOURCES.ORE]: 1 }
};

const DEV_CARD_TYPES = {
  KNIGHT: 'Knight',
  VICTORY_POINT: 'Victory Point',
  YEAR_OF_PLENTY: 'Year of Plenty',
  MONOPOLY: 'Monopoly',
  ROAD_BUILDING: 'Road Building'
};

const INITIAL_DEV_CARDS = [
  ...Array(14).fill(DEV_CARD_TYPES.KNIGHT),
  ...Array(5).fill(DEV_CARD_TYPES.VICTORY_POINT),
  ...Array(2).fill(DEV_CARD_TYPES.YEAR_OF_PLENTY),
  ...Array(2).fill(DEV_CARD_TYPES.MONOPOLY),
  ...Array(2).fill(DEV_CARD_TYPES.ROAD_BUILDING)
];

module.exports = {
  RESOURCES,
  PORT_TYPES,
  INITIAL_PORTS,
  BUILDING_COSTS,
  DEV_CARD_TYPES,
  INITIAL_DEV_CARDS
};